substitutions:
  name: bt-proxy-living-room
  room_slug: living_room

  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_domain: !secret wifi_domain

  api_encryption_key: ZLmO2PZH61H2MyzDlLJvvmY5bR/cWe481ytshR95Okc=
  ota_password: ebf49ffdd7d4fd579be64d83a5c13eea

  mqtt_broker: !secret mqtt_broker
  mqtt_username: !secret mqtt_username
  mqtt_password: !secret mqtt_password

packages:
  bt-proxy: !include packages/bt_proxy.yaml
