substitutions:
  name: bt-proxy-bedroom
  room_slug: bedroom

  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_domain: !secret wifi_domain

  api_encryption_key: L7J8U34XKN3LIwNouO1FAp/Fhu7MgGcyEIDT+pDCqsc=
  ota_password: fa59af1bc0c2891b6348e3e2383790a8

  mqtt_broker: !secret mqtt_broker
  mqtt_username: !secret mqtt_username
  mqtt_password: !secret mqtt_password

packages:
  bt-proxy: !include packages/bt_proxy.yaml

mqtt:
  log_topic:
    level: INFO